#!/bin/sh /etc/rc.common
START=70
STOP=15
PROG=/usr/sbin/inetacd.lua
USE_PROCD=1
start_service() {
procd_open_instance
procd_set_param command /usr/bin/lua "$PROG"
procd_close_instance
}
service_triggers() {
procd_add_reload_trigger "firewall"
}
